### PR TITLE
Update session.js

### PR DESCRIPTION
**Pull request by DenisGorbachev**
Refs #17

### CODE REVIEW

**Comment by DenisGorbachev** [comment]
I've tested it locally, seems to work :)

**Comment by DenisGorbachev** [comment]
@arunoda Could you please merge it and update MUP with that fix?

A little background: currently, the `TypeError: Object #<Socket> has no method 'clearLine'` originating from nodemiral breaks our continuous deployment pipeline. The error is fixed in this PR. So it would be great if you could merge it :)

**Comment by arunoda** [comment]
Thanks sure. This PR got lost in my inbox. 
Doing this now.

**Comment by DenisGorbachev** [comment]
Thank you!

On Fri, Sep 25, 2015 at 1:39 PM Arunoda Susiripala <notifications@github.com>
wrote:

> Thanks sure. This PR got lost in my inbox.
> Doing this now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arunoda/nodemiral/pull/18#issuecomment-143184439>.
>
-- 
Denis Gorbachev
CEO of BackupHamster <https://backuphamster.com/>

**Comment by arunoda** [comment]
I publish new versions of mup and mupx with this fix. Would you mind asking users to use the new version and it has your fix :)

**Comment by DenisGorbachev** [comment]
Er, could you please explain again what I should do?

On Fri, Sep 25, 2015 at 1:53 PM Arunoda Susiripala <notifications@github.com>
wrote:

> I publish new versions of mup and mupx with this fix. Would you mind
> asking users to use the new version and it has your fix :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arunoda/nodemiral/pull/18#issuecomment-143186507>.
>
-- 
Denis Gorbachev
CEO of BackupHamster <https://backuphamster.com/>

**Pull request merged**
